/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseLoading: typeof import('./components/BaseComponents/BaseLoading.vue')['default']
    BaseNoticeBar: typeof import('./components/BaseComponents/BaseNoticeBar.vue')['default']
    Button1: typeof import('./components/Button/Button1.vue')['default']
    Loading1: typeof import('./components/Loading/Loading1.vue')['default']
    Loading10: typeof import('./components/Loading/Loading10.vue')['default']
    Loading11: typeof import('./components/Loading/Loading11.vue')['default']
    Loading12: typeof import('./components/Loading/Loading12.vue')['default']
    Loading13: typeof import('./components/Loading/Loading13.vue')['default']
    Loading14: typeof import('./components/Loading/Loading14.vue')['default']
    Loading15: typeof import('./components/Loading/Loading15.vue')['default']
    Loading16: typeof import('./components/Loading/Loading16.vue')['default']
    Loading17: typeof import('./components/Loading/Loading17.vue')['default']
    Loading2: typeof import('./components/Loading/Loading2.vue')['default']
    Loading3: typeof import('./components/Loading/Loading3.vue')['default']
    Loading4: typeof import('./components/Loading/Loading4.vue')['default']
    Loading5: typeof import('./components/Loading/Loading5.vue')['default']
    Loading6: typeof import('./components/Loading/Loading6.vue')['default']
    Loading7: typeof import('./components/Loading/Loading7.vue')['default']
    Loading8: typeof import('./components/Loading/Loading8.vue')['default']
    Loading9: typeof import('./components/Loading/Loading9.vue')['default']
    PopBase: typeof import('./components/Popups/popBase.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanNoticeBar: typeof import('vant/es')['NoticeBar']
    VanPopup: typeof import('vant/es')['Popup']
  }
}
